language: python

cache:
    apt: true

addons:
    apt:
        packages:
            - gfortran

apt:
  packages:
    - gfortran

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - PANDAS: 0.22
    - SCIKIT-LEARN: 0.19.0
    env:
    - FLAKE8: true

before_install: source ci_scripts/install.sh

install: if [ -z ${FLAKE8} ]; then pip install -e .; fi

script:
  - if [ -z ${FLAKE8} ]; then
    py.test --cov=chainladder chainladder -v;
    else
    echo $PATH;
    which flake8;
    ci_scripts/flake8_diff.sh;
    fi;

after_success:
  - if [ -z ${FLAKE8} ]; then codecov; fi
