# The basic requirements for developing chainladder
name: cl_dev

channels:
  - defaults
  - conda-forge
  - r

dependencies:
  - python
  - pip
  - git
  - ipykernel

  - pandas>=0.23
  - scikit-learn>=0.23
  - sparse>=0.9
  - dill
  - xlcompose
  - patsy

  # Docs
  - seaborn
  - nbsphinx
  - numpydoc

  # testing
  - lxml
  - pytest
  - pytest-cov
  - black
  - rpy2
  - r-foreign
  - r-ggplot2
  - r-car
  - r-actuar
  - r-sandwich


  - pip:
    - sphinx_gallery
