# The basic requirements for building the hosted docs
name: cl_docs

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - pip
  - git

  - pandas==1.4.4
  - scikit-learn==1.1.3
  - sparse==0.13.0
  - numba==0.55.1
  - dill
  - patsy
  - statsmodels
  - matplotlib==3.5.3

  # Docs
  - ipython
  - parso>=0.8
  - nbsphinx
  - numpydoc

  - pip:
    - git+https://github.com/casact/chainladder-python/
    - jupyter-book
    - nb_black
    - sphinx-togglebutton
