# The basic requirements for CI testing of chainladder
name: cl_test

channels:
  - defaults
  - conda-forge
  - r

dependencies:
  - python

  # Downgrade numpy for rpy2 support
  - numpy
  - pandas
  - scikit-learn
  - sparse
  - numba
  - dill
  - patsy
  - dask

  # testing
  - lxml
  - pytest
  - pytest-cov
  - pip
  - ipython

