# The basic requirements for CI testing of chainladder
name: cl_test

channels:
  - defaults
  - conda-forge
  - r

dependencies:
  - python

  # Downgrade numpy for rpy2 support
  - numpy
  - pandas
  - scikit-learn
  - sparse
  - dill
  - patsy
  - dask

  # testing
  - lxml
  - pytest
  - pytest-cov
  - pip

  # R ChainLadder unit testing
  - tzlocal
  - libiconv
  - r-nloptr
  - r-matrix
  - r-reshape2
  - r-lattice
  - r-latticeextra
  - r-gridbase
  - r-gridextra
  - r-ggplot2
  - r-mass
  - r-rcppeigen
  - r-lme4
  - r-sparsem
  - r-matrixmodels
  - r-mgcv
  - r-nnet
  - r-pbkrtest
  - r-quantreg
  - r-zoo
  - r-car
  - r-lmtest
  - r-sandwich
  - r-coda
  - r-minqa
  - r-foreign
  - r-actuar
  - r-biglm
  - r-tweedie
  - r-statmod
  - r-cplm
  - pip:
    - rpy2
