# The basic requirements for CI testing of chainladder
name: cl_test

channels:
  - defaults
  - conda-forge

dependencies:
  - pandas>=0.23
  - scikit-learn>=0.23
  - sparse>=0.9
  - numba
  - dill
  - patsy
  - dask

  # testing
  - lxml
  - pytest
  - pytest-cov
  - ipython

